-- ============================================================
-- Base schema: every table and database function the backend uses
-- ============================================================
-- Exported from the live database on 2026-10-02 (public schema only, structure only, no data)
-- and tidied without changing behaviour: indexes that duplicated another index or a key were
-- dropped, and leftover defaults were removed from foreign key columns (the backend always
-- sets them; a random uuid there could never satisfy the foreign key anyway).
-- Tables are ordered so that each one is created after the tables it references.
--
-- Fresh install: run this file once in the Supabase SQL editor, then run only the pg_cron
-- steps (the scheduled clean-up jobs) of kvkk_temizlik.sql (two jobs), kvkk_riza.sql and
-- memnuniyet_anketleri.sql. gorev_etaplari.sql also describes an optional job that is off on
-- purpose. Everything else in the db/*.sql files is a migration for older databases and is
-- already included here.
--
-- Row level security is enabled on every table and there are no policies. That is deliberate:
-- the backend connects with the service_role key, which bypasses RLS, and the browser never
-- talks to the database directly, so the public (anon) key can read nothing.
-- ============================================================


CREATE TABLE public.firmalar (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  firma_adi text NOT NULL,
  kayit_tarihi timestamp without time zone DEFAULT now(),
  merkez_lat double precision,
  merkez_lng double precision,
  is_active boolean DEFAULT true,
  sistem_modu text DEFAULT 'HARITA'::text,
  subeli boolean DEFAULT false,
  max_sube integer DEFAULT 0,
  toplam_kota integer DEFAULT 1,
  vale_aktif boolean DEFAULT false,
  shuttle_aktif boolean DEFAULT true,
  vale_kota integer DEFAULT 0,
  kvkk_unvan text,
  kvkk_basvuru_kanali text,
  kvkk_adres text,
  kvkk_riza_gerekli boolean DEFAULT true NOT NULL,
  CONSTRAINT firmalar_pkey PRIMARY KEY (id)
);

CREATE TABLE public.subeler (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  firma_id uuid NOT NULL,
  sube_adi text NOT NULL,
  aktif_kota integer DEFAULT 0 NOT NULL,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  konum_lat double precision,
  konum_lng double precision,
  CONSTRAINT subeler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id),
  CONSTRAINT subeler_pkey PRIMARY KEY (id)
);

CREATE TABLE public.guzergahlar (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  firma_id uuid NOT NULL,
  guzergah_adi text NOT NULL,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  tip text,
  sube_id uuid,
  CONSTRAINT guzergahlar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id),
  CONSTRAINT guzergahlar_pkey PRIMARY KEY (id),
  CONSTRAINT guzergahlar_sube_id_fkey FOREIGN KEY (sube_id) REFERENCES subeler(id)
);

CREATE TABLE public.araclar (
  id text NOT NULL,
  plaka text,
  saat text,
  son_lat double precision,
  son_lng double precision,
  firma_id uuid,
  marka text DEFAULT 'Genel'::text,
  rota_aktif boolean DEFAULT false,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  son_durak_lat double precision,
  son_durak_lng double precision,
  guzergah_id uuid,
  son_hareket_zamani timestamp with time zone,
  durum text DEFAULT 'MERKEZDE'::text,
  hareket_saati text,
  sube_id uuid,
  tip text DEFAULT 'SERVIS'::text,
  CONSTRAINT araclar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id) ON DELETE CASCADE,
  CONSTRAINT araclar_guzergah_id_fkey FOREIGN KEY (guzergah_id) REFERENCES guzergahlar(id),
  CONSTRAINT araclar_pkey PRIMARY KEY (id),
  CONSTRAINT araclar_sube_id_fkey FOREIGN KEY (sube_id) REFERENCES subeler(id)
);

CREATE TABLE public.duraklar (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  guzergah_id uuid NOT NULL,
  durak_adi text NOT NULL,
  konum_lat double precision,
  konum_lng double precision,
  firma_id uuid,
  sira_no integer DEFAULT 0,
  CONSTRAINT duraklar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id),
  CONSTRAINT duraklar_guzergah_id_fkey FOREIGN KEY (guzergah_id) REFERENCES guzergahlar(id),
  CONSTRAINT duraklar_pkey PRIMARY KEY (id)
);

CREATE TABLE public.arac_saat_sablonlari (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  arac_id text NOT NULL,
  saat text,
  firma_id uuid,
  CONSTRAINT arac_saat_sablonlari_arac_id_fkey FOREIGN KEY (arac_id) REFERENCES araclar(id),
  CONSTRAINT arac_saat_sablonlari_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id),
  CONSTRAINT arac_saat_sablonlari_pkey PRIMARY KEY (id)
);

CREATE TABLE public.kullanicilar (
  kullanici_adi text NOT NULL,
  sifre text,
  rol text,
  arac_id text,
  firma_id uuid,
  marka text DEFAULT 'Genel'::text,
  davet_token text,
  telefon text,
  email text,
  kayit_tarihi timestamp with time zone DEFAULT now(),
  davet_token_olusturma timestamp with time zone,
  is_active boolean DEFAULT true,
  sube_id uuid,
  gorunen_ad character varying(60),
  CONSTRAINT kullanicilar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id) ON DELETE CASCADE,
  CONSTRAINT kullanicilar_pkey PRIMARY KEY (kullanici_adi),
  CONSTRAINT kullanicilar_sube_id_fkey FOREIGN KEY (sube_id) REFERENCES subeler(id)
);

CREATE TABLE public.markalar (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  firma_id uuid NOT NULL,
  marka_adi text,
  sube_id uuid,
  CONSTRAINT markalar_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id) ON DELETE CASCADE,
  CONSTRAINT markalar_pkey PRIMARY KEY (id),
  CONSTRAINT markalar_sube_id_fkey FOREIGN KEY (sube_id) REFERENCES subeler(id)
);

CREATE TABLE public.talepler (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  token text,
  musteri_ad text,
  arac_id text,
  durum text DEFAULT 'BEKLİYOR'::text,
  konum_lat double precision,
  konum_lng double precision,
  kayit_tarihi timestamp with time zone DEFAULT timezone('utc'::text, now()),
  marka_id integer,
  gorev_tipi text,
  firma_id uuid,
  mesafe_km double precision,
  marka text DEFAULT 'Genel'::text,
  musteri_tel text,
  secilen_durak_id uuid,
  sube_id uuid,
  musteri_plaka text DEFAULT ''::text,
  iliskili_talep_id uuid,
  serviste_kapandi boolean DEFAULT false,
  tamamlanma_tarihi timestamp with time zone,
  riza_alindi boolean DEFAULT false NOT NULL,
  riza_reddedildi boolean DEFAULT false NOT NULL,
  CONSTRAINT talepler_arac_id_fkey FOREIGN KEY (arac_id) REFERENCES araclar(id),
  CONSTRAINT talepler_firma_id_fkey FOREIGN KEY (firma_id) REFERENCES firmalar(id) ON DELETE CASCADE,
  CONSTRAINT talepler_pkey PRIMARY KEY (id),
  CONSTRAINT talepler_sube_id_fkey FOREIGN KEY (sube_id) REFERENCES subeler(id),
  CONSTRAINT talepler_token_key UNIQUE (token)
);

CREATE TABLE public.audit_log (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  yapan_kullanici_adi text,
  yapan_rol text,
  yapan_firma_id uuid,
  yapan_ip text,
  eylem text NOT NULL,
  hedef_tip text,
  hedef_id text,
  hedef_aciklama text,
  detay jsonb,
  basarili boolean DEFAULT true,
  tarih timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE public.revoked_tokens (
  jti text NOT NULL,
  kullanici_adi text NOT NULL,
  sebep text,
  iptal_eden text,
  iptal_tarihi timestamp with time zone DEFAULT now() NOT NULL,
  expire_tarihi timestamp with time zone NOT NULL,
  CONSTRAINT revoked_tokens_pkey PRIMARY KEY (jti)
);

CREATE TABLE public.kullanici_token_iptal (
  kullanici_adi text NOT NULL,
  gecersiz_before timestamp with time zone NOT NULL,
  sebep text,
  guncelleme_tarihi timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT kullanici_token_iptal_pkey PRIMARY KEY (kullanici_adi)
);

CREATE TABLE public.gorev_etaplari (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  talep_id uuid,
  firma_id uuid,
  sube_id uuid,
  arac_id uuid,
  vale_kullanici_adi text,
  gorev_tipi text NOT NULL,
  etap text NOT NULL,
  baslangic timestamp with time zone NOT NULL,
  hedef_varis timestamp with time zone,
  hedef_dakika integer,
  gercek_varis timestamp with time zone,
  sapma_dk integer,
  mesafe_km numeric(6,2),
  basma_mesafe_m integer,
  iptal_edildi boolean DEFAULT false NOT NULL,
  kayit_tarihi timestamp with time zone DEFAULT now() NOT NULL,
  konum_bildirildi boolean,
  basma_konum_yasi_sn integer,
  basma_dogruluk_m integer,
  marka text,
  CONSTRAINT etap_gecerli CHECK ((etap = ANY (ARRAY['MUSTERIYE_GIDIS'::text, 'SERVISE_DONUS'::text, 'SERVIS_HAZIRLIK'::text, 'MUSTERIYE_TESLIM'::text]))),
  CONSTRAINT etap_gorev_tipi_gecerli CHECK ((gorev_tipi = ANY (ARRAY['VALE_ALIM'::text, 'VALE_TESLIM'::text]))),
  CONSTRAINT gorev_etaplari_pkey PRIMARY KEY (id)
);

CREATE TABLE public.memnuniyet_anketleri (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  talep_id uuid,
  firma_id uuid,
  sube_id uuid,
  arac_id uuid,
  vale_kullanici_adi text,
  gorev_tipi text NOT NULL,
  puan_genel smallint NOT NULL,
  puan_dakiklik smallint,
  puan_ilgi smallint,
  puan_arac_durumu smallint,
  puan_bilgilendirme smallint,
  yorum text,
  yorum_yazildi boolean DEFAULT false NOT NULL,
  kayit_tarihi timestamp with time zone DEFAULT now() NOT NULL,
  marka text,
  CONSTRAINT anket_gorev_tipi_gecerli CHECK ((gorev_tipi = ANY (ARRAY['VALE_ALIM'::text, 'VALE_TESLIM'::text]))),
  CONSTRAINT anket_puan_arac_araligi CHECK (((puan_arac_durumu IS NULL) OR ((puan_arac_durumu >= 1) AND (puan_arac_durumu <= 5)))),
  CONSTRAINT anket_puan_bilgi_araligi CHECK (((puan_bilgilendirme IS NULL) OR ((puan_bilgilendirme >= 1) AND (puan_bilgilendirme <= 5)))),
  CONSTRAINT anket_puan_dakiklik_araligi CHECK (((puan_dakiklik IS NULL) OR ((puan_dakiklik >= 1) AND (puan_dakiklik <= 5)))),
  CONSTRAINT anket_puan_genel_araligi CHECK (((puan_genel >= 1) AND (puan_genel <= 5))),
  CONSTRAINT anket_puan_ilgi_araligi CHECK (((puan_ilgi IS NULL) OR ((puan_ilgi >= 1) AND (puan_ilgi <= 5)))),
  CONSTRAINT anket_yorum_uzunlugu CHECK (((yorum IS NULL) OR (char_length(yorum) <= 500))),
  CONSTRAINT memnuniyet_anketleri_pkey PRIMARY KEY (id),
  CONSTRAINT memnuniyet_anketleri_talep_id_key UNIQUE (talep_id)
);

CREATE TABLE public.riza_kayitlari (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  firma_id uuid,
  talep_id uuid,
  kullanici_adi text,
  kanal text NOT NULL,
  islem text NOT NULL,
  metin_kodu text NOT NULL,
  metin_versiyonu text NOT NULL,
  ip_adresi text,
  user_agent text,
  kayit_tarihi timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT riza_islem_gecerli CHECK ((islem = ANY (ARRAY['ONAY'::text, 'RED'::text, 'GERI_CEKME'::text]))),
  CONSTRAINT riza_kanal_gecerli CHECK ((kanal = ANY (ARRAY['YOLCU_KONUM'::text, 'VALE_KONUM'::text, 'PERSONEL_HESAP'::text]))),
  CONSTRAINT riza_kayitlari_pkey PRIMARY KEY (id)
);


-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------

CREATE INDEX idx_anket_firma ON public.memnuniyet_anketleri USING btree (firma_id, kayit_tarihi DESC);
CREATE INDEX idx_anket_marka ON public.memnuniyet_anketleri USING btree (firma_id, marka, kayit_tarihi DESC);
CREATE INDEX idx_anket_vale ON public.memnuniyet_anketleri USING btree (vale_kullanici_adi, kayit_tarihi DESC);
CREATE INDEX idx_araclar_firma_id ON public.araclar USING btree (firma_id);
CREATE INDEX idx_araclar_plaka ON public.araclar USING btree (plaka);
CREATE INDEX idx_audit_eylem ON public.audit_log USING btree (eylem, tarih DESC);
CREATE INDEX idx_audit_firma ON public.audit_log USING btree (yapan_firma_id, tarih DESC);
CREATE INDEX idx_audit_tarih ON public.audit_log USING btree (tarih DESC);
CREATE INDEX idx_audit_yapan ON public.audit_log USING btree (yapan_kullanici_adi, tarih DESC);
CREATE INDEX idx_etap_firma ON public.gorev_etaplari USING btree (firma_id, baslangic DESC);
CREATE INDEX idx_etap_marka ON public.gorev_etaplari USING btree (firma_id, marka, baslangic DESC);
CREATE INDEX idx_etap_talep ON public.gorev_etaplari USING btree (talep_id, baslangic);
CREATE INDEX idx_etap_vale ON public.gorev_etaplari USING btree (vale_kullanici_adi, baslangic DESC);
CREATE INDEX idx_kullanicilar_davet_token ON public.kullanicilar USING btree (davet_token);
CREATE INDEX idx_kullanicilar_firma_id ON public.kullanicilar USING btree (firma_id);
CREATE INDEX idx_revoked_expire ON public.revoked_tokens USING btree (expire_tarihi);
CREATE INDEX idx_revoked_kullanici ON public.revoked_tokens USING btree (kullanici_adi);
CREATE INDEX idx_riza_firma ON public.riza_kayitlari USING btree (firma_id, kayit_tarihi DESC);
CREATE INDEX idx_riza_talep ON public.riza_kayitlari USING btree (talep_id, kayit_tarihi DESC);
CREATE INDEX idx_riza_tarih ON public.riza_kayitlari USING btree (kayit_tarihi);
CREATE INDEX idx_subeler_firma ON public.subeler USING btree (firma_id);
CREATE INDEX idx_talepler_arac_id ON public.talepler USING btree (arac_id);
CREATE INDEX idx_talepler_durum ON public.talepler USING btree (durum);
CREATE INDEX idx_talepler_firma_id ON public.talepler USING btree (firma_id);
CREATE INDEX idx_talepler_kayit_tarihi ON public.talepler USING btree (kayit_tarihi);

-- A vehicle can have at most one driver account.
CREATE UNIQUE INDEX unique_aktif_sofor_arac ON public.kullanicilar USING btree (arac_id) WHERE ((arac_id IS NOT NULL) AND (rol = 'SOFOR'::text));


-- ------------------------------------------------------------
-- Row level security: enabled everywhere, no policies (see the header)
-- ------------------------------------------------------------

ALTER TABLE public.arac_saat_sablonlari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.araclar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.duraklar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.firmalar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gorev_etaplari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guzergahlar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kullanici_token_iptal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kullanicilar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.markalar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memnuniyet_anketleri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revoked_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.riza_kayitlari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subeler ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.talepler ENABLE ROW LEVEL SECURITY;


-- ------------------------------------------------------------
-- Stop functions, called by the backend through .rpc()
-- ------------------------------------------------------------
-- Inserting or deleting a stop shifts the sira_no of every later stop on the same route.
-- Doing that in one function call keeps it in a single transaction and locks the route's
-- stops, so two admins editing the same route at once cannot produce duplicate or missing
-- sequence numbers.

CREATE OR REPLACE FUNCTION public.atomik_durak_ekle(p_guzergah_id uuid, p_firma_id uuid, p_durak_adi text, p_konum_lat numeric, p_konum_lng numeric, p_sira_no integer)
 RETURNS TABLE(id uuid, durak_adi text, sira_no integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Lock the other stops on this route (prevents a race condition)
    PERFORM 1 FROM duraklar
    WHERE duraklar.guzergah_id = p_guzergah_id
    FOR UPDATE;

    -- Qualify sira_no with "duraklar." so it is not confused with the sira_no in RETURNS TABLE
    UPDATE duraklar
    SET sira_no = duraklar.sira_no + 1
    WHERE duraklar.guzergah_id = p_guzergah_id
      AND duraklar.sira_no >= p_sira_no;

    -- Insert the new stop and return it
    RETURN QUERY
    INSERT INTO duraklar (guzergah_id, firma_id, durak_adi, konum_lat, konum_lng, sira_no)
    VALUES (p_guzergah_id, p_firma_id, p_durak_adi, p_konum_lat, p_konum_lng, p_sira_no)
    RETURNING duraklar.id, duraklar.durak_adi, duraklar.sira_no;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.atomik_durak_sil(p_durak_id uuid)
 RETURNS TABLE(silinen_durak_id uuid, kalan_durak_sayisi integer)
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_guzergah_id UUID;
    v_silinen_sira INTEGER;
    v_kalan_sayi INTEGER;
BEGIN
    -- 1. Read the route and sequence number of the stop being deleted
    SELECT guzergah_id, sira_no INTO v_guzergah_id, v_silinen_sira
    FROM duraklar
    WHERE id = p_durak_id;

    IF v_guzergah_id IS NULL THEN
        RAISE EXCEPTION 'Durak bulunamadı: %', p_durak_id;
    END IF;

    -- 2. Lock the other stops on this route (prevents a race condition)
    PERFORM 1 FROM duraklar
    WHERE guzergah_id = v_guzergah_id
    FOR UPDATE;

    -- 3. Delete the stop
    DELETE FROM duraklar WHERE id = p_durak_id;

    -- 4. Move every later stop up by one
    UPDATE duraklar
    SET sira_no = sira_no - 1
    WHERE guzergah_id = v_guzergah_id
      AND sira_no > v_silinen_sira;

    -- 5. Return how many stops are left
    SELECT COUNT(*) INTO v_kalan_sayi
    FROM duraklar
    WHERE guzergah_id = v_guzergah_id;

    RETURN QUERY SELECT p_durak_id, v_kalan_sayi::INTEGER;
END;
$function$
;


-- ------------------------------------------------------------
-- Clean-up functions
-- ------------------------------------------------------------
-- Each deletes old rows and returns how many it deleted. Neither the backend nor any pg_cron
-- job calls them (checked 2026-10-02); they are kept because they exist in the live database.

-- Audit log entries older than 6 months.
CREATE OR REPLACE FUNCTION public.eski_audit_loglarini_temizle()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    silinen_sayi INTEGER;
BEGIN
    DELETE FROM audit_log WHERE tarih < NOW() - INTERVAL '6 months';
    GET DIAGNOSTICS silinen_sayi = ROW_COUNT;
    RETURN silinen_sayi;
END;
$function$
;

-- Revoked tokens that have expired anyway (an expired token is rejected without the list).
CREATE OR REPLACE FUNCTION public.expire_olan_revoked_temizle()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    silinen_sayi INTEGER;
BEGIN
    DELETE FROM revoked_tokens WHERE expire_tarihi < NOW();
    GET DIAGNOSTICS silinen_sayi = ROW_COUNT;
    RETURN silinen_sayi;
END;
$function$
;
